name: Sync with OpenCC

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 4 2 * *'
    
  
  workflow_dispatch:

  push:
    branches:
      - bot
          

jobs:
  my_first_job_id:
    name: My first job
    runs-on: ubuntu-latest
    steps:
    - name: Job's checkout
      uses: actions/checkout@master
      
    - name: Show some info and switch branch
      run: |
        uname -a
        cat /etc/os-release
        pwd
        ls -la
        git branch -a
        git fetch origin main
        git branch -a
        git config user.name bot
        git config user.email bot@github.bot.none
        git config --list
        env
        dpkg --list
        df -Th
        mount
        echo $$
        ps axfj
        cat /proc/cpuinfo
        
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
      
    - name: Run the bash
      run: bash fetch-opencc.sh
        
